document:
  name: Linee Guida normalizzazione statistiche
  description: |
    Linee Guida per la normalizzazione dei dati statistici dei servizi erogati dai Gestori PEC, dai Conservatori e dai Prestatori di servizi fiduciari qualificati
  tags:
    - "SPID"
