document:
  name: Linee Guida normalizzazione statistiche
  description: |
    Linee Guida per la normalizzazione delle statistiche dei servizi fiduciari elettronici, di SPID e della PEC
  tags:
    - "SPID"
