document:
  type: Linee guida
  name: Linee guida per la normalizzazione delle statistiche sui servizi erogati da gestori PEC, conservatori, prestatori di servizi fiduciari qualificati
  short_name: Ll.gg. sulle statistiche PEC conservatori QTSP
  author: walter-arrighetti
  contributors:
    - Gabriele Bocchetta
    - Stefano Arbia
    - Walter Arrighetti
    - Michele D'Amico
    - Antonio Florio
    - Stefano Ianniello
    - Andrea Spallacci
    - Crisina Valiante
  description: |
    Linee guida per la normalizzazione delle statistiche sui servizi erogati da gestori PEC, conservatori, prestatori di servizi fiduciari qualificati
  tags:
    - eIDAS
    - PEC
    - conservazione
    - servizi fiduciari elettronici
    - SPID
    - statistiche
    - GDPR
  origin: https://github.com/test-lg/lg-qtsp-pec-statistiche-docs
